kind: pipeline
name: default
type: kubernetes 

steps:
- name: test
  image: docker:dind
  volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
  commands:
  - apk add --no-cache curl jq
  - chmod +x remove_images.sh
  - ./remove_images.sh
services:
- name: docker
  image: docker:dind
  privileged: false
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
 
  



    
  
