kind: pipeline
name: default

steps:
- name: test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - UNAME="abdelhakavaxia"
  - TOKEN="dckr_pat_nmj1n6g5nQF07n7w5VHVaYsanTI"
  - echo "$UNAME"
  - echo "$TOKEN"
  - tag=$(curl -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${UNAME}/election-app-front-end/tags/?page_size=100 | jq -r '.results|.[]|.name'| head  )
  - echo "$tag"
  - num_tags=$(echo "$tag" | wc -l)
  - echo "$num_tags"
  - if [ $num_tags -gt 2 ] then most_recent_tags=$(curl -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${UNAME}/election-app-front-end/tags/?page_size=100 | jq -r '.results|.[]|.name'| head -n 2)
    echo "$most_recent_tags"
    nbrtagsupp=$((${num_tags} - 2))
    echo "$nbrtagsupp"
    tagsupp=$(curl -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${UNAME}/election-app-front-end/tags/?page_size=100 | jq -r '.results|.[]|.name'| tail -n ${nbrtagsupp})
    echo "$tagsupp"
    fi
  - for j in ${tagsupp} 
     do
        docker run --rm -it lumir/remove-dockerhub-tag --user ${UNAME}  --password ${TOKEN}   abdelhakavaxia/election-app-front-end/:${j} 
     done

  - sleep 5 # give docker enough time to start
  - docker ps -a

services:
- name: docker
  image: docker:dind
  privileged: false
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
    

    
  
