kind: pipeline
name: default
type: kubernetes

steps:
- name: test
  image: docker:dind
  environment:
       DOCKER_HOST: unix:///var/run/docker.sock
       UNAME: abdelhakavaxia
       TOKEN: dckr_pat_nmj1n6g5nQF07n7w5VHVaYsanTI
       REPO: abdelhakavaxia/election-app-front-end
  volumes:
  - name: dockersock
    path: /var/run/
  commands:
     - apk add --update curl jq
     - docker login -u $UNAME -p $TOKEN
     - chmod +x remove_images.sh
     - ./remove_images.sh


 

services:
- name: docker
  image: docker:dind
  privileged: false
  volumes:
  - name: dockersock
    path: /var/run/

volumes:
- name: dockersock
  temp: {}

