kind: pipeline
name: remove-images
type: kubernetes 
steps:
  - name: remove-images
    image: ceregousa/dind
    volumes:
      - name: dockersock 
        path: /var/run/
    environment:
       UNAME: abdelhakavaxia
       TOKEN: dckr_pat_nmj1n6g5nQF07n7w5VHVaYsanTI
       REPO: abdelhakavaxia/election-app-front-end
    commands:
      - apk add --update curl jq

      - docker login -u $UNAME -p $TOKEN
      - chmod +x remove_images.sh
      - ./remove_images.sh
services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
volumes:
- name: dockersock
  temp: {}

